# Site settings
title: "Circuits And Other Writings"
#email: jacob@jacobtomlinson.co.uk
#description: "A dark blog theme for Jekyll."
baseurl: ""
url: "https://flyingtoaster0.github.io/"
title_description: "A blog archiving my projects and other such things."
title_image: "http://www.gravatar.com/avatar/644f890d44e6d524da53b455bbcd52d3?s=500&d=mm"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
#github_repository: https://github.com/jacobtomlinson/carte-noire
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: flyingtoaster0
github_username:  flyingtoaster0
#linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
#stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
